apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aivis-chan-bot-web-data-pvc
  labels:
    app: aivis-chan-bot-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
