apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-reverse-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-reverse-proxy-config
  labels:
    app: nginx-reverse-proxy
  
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      location / {
        proxy_pass http://aivis-chan-bot-web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
spec:
  type: NodePort
  selector:
    app: nginx-reverse-proxy
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
