apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aivisspeech-data-pvc
  labels:
    app: aivisspeech-engine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-static
