apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: funya-mura-data-pvc-new
  namespace: mc-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
