apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lost-cities-data-pvc-new
  namespace: mc-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
  volumeMode: Filesystem
