# WARNING: Replace <BASE64_CREDENTIALS_JSON> with base64 of your credentials.json
# Don't commit the plain credentials.json into the repo. Prefer sealed-secrets / sops for production.
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
type: Opaque
data:
  # Put base64-encoded content of your credentials.json here
  credentials.json: "eyJBY2NvdW50VGFnIjoiZjc0ZjkzZDI2NWQ3ZTRiZDkxMWFhNDQ5MzQ3OTVhYjYiLCJUdW5uZWxTZWNyZXQiOiJ5aFdmVWtsOXFBWGdoayt4M2FDczZTQnlxa0tKRHg1U1pnYjJtVzFpTU1rPSIsIlR1bm5lbElEIjoiMzE4NWI2Y2UtMWExNy00YjY4LWFjNTgtZTE3ZTg4NzIyM2JmIiwiRW5kcG9pbnQiOiIifQ=="
